In [1]:
import os
import sys
import time
import torch
import faulthandler

from tqdm import tqdm

faulthandler.enable()

In [2]:
os.environ["PYTHONUTF8"] = "1"
os.environ['TORCHDYNAMO_VERBOSE'] = "1"
os.environ["PYTHONIOENCODING"] = "utf-8"

torch._dynamo.config.verbose = True
torch._dynamo.config.suppress_errors = False
torch.set_float32_matmul_precision('high')

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
print(torch.__version__)
print(torch.version.cuda)

2.7.0+cu128
12.8


In [5]:
sys.path.insert(0, os.path.abspath(os.path.join(os.path.curdir, '..')))

In [6]:
from model.arvane import (
    ArvaneModel
)
from model.utils import(
    load_config
)

In [7]:
config = load_config('../config/config.yml')

In [9]:
model = ArvaneModel(config).to(device)
model.load_state_dict(torch.load("../checkpoint/arvane.pt"))

<All keys matched successfully>

In [10]:
model.eval()
model = torch.compile(model)

In [11]:
model.depth_encoder.state_dict()

OrderedDict([('patch_encoder.cls_token',
              tensor([[[ 0.0062, -0.0025, -0.0065,  ..., -0.0049,  0.0036, -0.0014]]],
                     device='cuda:0')),
             ('patch_encoder.pos_embed',
              tensor([[[ 0.0062, -0.0025, -0.0065,  ..., -0.0049,  0.0036, -0.0014],
                       [-0.0065,  0.0116, -0.0003,  ...,  0.0114, -0.0080, -0.0041],
                       [ 0.0003,  0.0071, -0.0008,  ...,  0.0127, -0.0063,  0.0262],
                       ...,
                       [ 0.0018,  0.0007,  0.0038,  ...,  0.0002, -0.0035,  0.0090],
                       [ 0.0017,  0.0009,  0.0079,  ...,  0.0029, -0.0011,  0.0183],
                       [ 0.0108,  0.0030,  0.0157,  ...,  0.0032,  0.0007,  0.0238]]],
                     device='cuda:0')),
             ('patch_encoder.patch_embed.proj.weight',
              tensor([[[[ 2.2144e-03, -3.9673e-03, -2.9621e-03,  ..., -7.2908e-04,
                          1.7605e-03,  5.6076e-03],
                     